import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { InputText } from "primereact/inputtext";
import { Password } from "primereact/password";
import { Button } from "primereact/button";
import { useState, useEffect, useRef } from "react";
import { useRouter } from "next/router";
import loginStyle from "@/styles/Login.module.css";
import { loginPost } from "@/API/Request/login";
import { Toast } from "primereact/toast";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const router = useRouter();
  const toast = useRef(null);

  async function handleSubmit() {
    const response = await loginPost(email, password);
    if (response === 200) {
      router.push("/home");
    } else {
      toast.current.show({
        severity: "error",
        summary: "Error",
        detail: "Usuario o contraseña incorrectos",
        life: 3000,
      });
      setEmail("");
      setPassword("");
    }
    router.push("/home");
  }

  return (
    <>
      <Toast ref={toast} />
      <Head>
        <title>Clinica</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={`${loginStyle.loginForm}`}>
          <h1>Clinica</h1>
          <div className={`${loginStyle.fieldsContainer}`}>
            <div className={`${loginStyle.textField}`}>
              <label>Usuario:</label>
              <InputText
                placeholder="Usuario"
                value={email}
                onChange={(e) => setEmail(e.target.value)}
              />
            </div>

            <div className={`${loginStyle.textField}`}>
              <label>Contraseña:</label>
              <Password
                placeholder="Contraseña"
                value={password}
                onChange={(p) => setPassword(p.target.value)}
                toggleMask
                feedback={false}
              />
            </div>

            <Button
              label="Acceder"
              className="login-button"
              onClick={() => handleSubmit()}
            />
          </div>
        </div>
      </main>
    </>
  );
}
