import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { InputText } from "primereact/inputtext";
import { Password } from "primereact/password";
import { Button } from "primereact/button";
import { useState, useEffect } from "react";
import { useRouter } from "next/router";
import loginStyle from "@/styles/Login.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");

  return (
    <>
      <Head>
        <title>Clinica</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={`${loginStyle.loginForm}`}>
          <h1>Clinica</h1>
          <div className={`${loginStyle.fieldsContainer}`}>
            <div className={`${loginStyle.textField}`}>
              <label>Usuario:</label>
              <InputText
                placeholder="Usuario"
                value={email}
                onChange={(e) => setEmail(e.target.value)}
              />
            </div>

            <div className={`${loginStyle.textField}`}>
              <label>Contraseña:</label>
              <Password
                placeholder="Contraseña"
                value={password}
                onChange={(p) => setPassword(p.target.value)}
                toggleMask
                feedback={false}
              />
            </div>

            <Button
              label="Login"
              className="login-button"
              onClick={() => handleSubmit()}
            />
          </div>
        </div>
      </main>
    </>
  );
}
